//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetRentingEvent
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public Nullable<int> BookingSeatId { get; set; }
        public int AssetRentingId { get; set; }
    
        public virtual AssetRenting AssetRenting { get; set; }
        public virtual BookingSeat BookingSeat { get; set; }
        public virtual Event Event { get; set; }
    }
}
