//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Advertisement> Advertisements { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<AssetRenting> AssetRentings { get; set; }
        public virtual DbSet<AssetRentingEvent> AssetRentingEvents { get; set; }
        public virtual DbSet<BookingSeat> BookingSeats { get; set; }
        public virtual DbSet<Cleaning> Cleanings { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<Like> Likes { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<New> News { get; set; }
        public virtual DbSet<Parking> Parkings { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Renter> Renters { get; set; }
        public virtual DbSet<Renting> Rentings { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Seat> Seats { get; set; }
        public virtual DbSet<Security> Securities { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<STicketChat> STicketChats { get; set; }
        public virtual DbSet<STicketType> STicketTypes { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StorePM> StorePMs { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<SubscriptionLevel> SubscriptionLevels { get; set; }
        public virtual DbSet<SupportTicket> SupportTickets { get; set; }
        public virtual DbSet<Theater> Theaters { get; set; }
        public virtual DbSet<TheaterPM> TheaterPMs { get; set; }
        public virtual DbSet<TheaterService> TheaterServices { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
