//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int RentingID { get; set; }
        public string Type { get; set; }
        public double Amount { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Renting Renting { get; set; }
    }
}
