//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int AssetId { get; set; }
        public Nullable<int> Size { get; set; }
        public int StorePMId { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual StorePM StorePM { get; set; }
    }
}
